version: '3.7'

volumes:
   geoserver-data:

services:
   geoserver:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          GS_VERSION: 2.16.2
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8082:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m
        timeout: 10s
        retries: 3
        start_period: 1m
